# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.TextField(default=datetime.datetime(2016, 5, 18, 12, 2, 26, 503149, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
